### ISSUE TITLE
Chapter 19 - Binary Tree

### ISSUE THREAD

**Issue by johnmetzbower** [johnmetzbower/Microsoft_Visual_CSharp_Step_by_Step#1]
@mishfit  working in the binary tree project in Chapter19 they asked me to insert using directing 'using BinaryTree;' but when I did it gives me an error.  I don't know why since this is the first time I've used a using directive for a class that I made myself.  Can you help?

**Comment by mishfit** [comment]
I'm going to make an assumption: the "BinaryTree" namespace is of your
creation. If it isn't then you should be using the namespaces you have
defined in your binary tree project.

**Comment by johnmetzbower** [comment]
The BinaryTree  is a namespace  that was created in this project.

**Comment by mishfit** [comment]
Did you add the project, "BinaryTree" as a reference to the project "EnumeratorTest"? Both projects are in the same solution but that doesn't mean they reference each other (or in this case that EnumeratorTest references BinaryTree). The compilation error is in the EnumeratorTest project.

Did the compilation error state something like this, **_"The type or namespace 'BinaryTree' could not be found. Are you missing an assembly reference?"_**
